spring:
  datasource:
    username: root
    password: Wym200108
    url: jdbc:mysql://47.92.195.102:3306/dm_wxs?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name:  com.mysql.cj.jdbc.Driver
    ## Redis 配置
  redis:
      ## Redis数据库索引（默认为0）
      database: 0
      ## Redis服务器地址
      host: 47.92.195.102
      ## Redis服务器连接端口
      port: 6379
      ## Redis服务器连接密码（默认为空）
      password: Wym200108
      jedis:
        pool:
          ## 连接池最大连接数（使用负值表示没有限制）
          #spring.redis.pool.max-active=8
          max-active: 8
          ## 连接池最大阻塞等待时间（使用负值表示没有限制）
          #spring.redis.pool.max-wait=-1
          max-wait: -1
          ## 连接池中的最大空闲连接
          #spring.redis.pool.max-idle=8
          max-idle: 8
          ## 连接池中的最小空闲连接
          #spring.redis.pool.min-idle=0
          min-idle: 0
      ## 连接超时时间（毫秒）
      timeout: 1200
#mybatis配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: wxs.*.po
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    #配置的缓存的全局开关
    cache-enabled: true
    #延时加载的开关
    lazyLoadingEnabled: true
    #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    multipleResultSetsEnabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true

